backend:
  name: git-gateway
  branch: main  # หรือ branch ที่คุณใช้

media_folder: "images/uploads"      # ที่เก็บไฟล์อัพโหลดใน repo
public_folder: "/test1/images/uploads"    # path สำหรับแสดงผลบนเว็บ

collections:
  - name: "products"
    label: "สินค้า"
    folder: "products"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "ชื่อสินค้า", name: "title", widget: "string" }
      - { label: "รายละเอียด", name: "body", widget: "markdown" }
      - { label: "ภาพสินค้า", name: "image", widget: "image" }
      - { label: "ราคา", name: "price", widget: "string" }
      - { label: "แสดงในหน้าแรก", name: "featured", widget: "boolean", required: false }