backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "สินค้า"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ชื่อสินค้า", name: "title", widget: "string" }
      - { label: "คำอธิบาย", name: "description", widget: "text" }
      - { label: "รูปภาพ", name: "image", widget: "image" }
      - { label: "ราคา", name: "price", widget: "string" }
