backend:
  name: git-gateway
  branch: main  # หรือ branch ที่คุณใช้

media_folder: "images/uploads"
public_folder: "/test1/images/uploads"

collections:
  - name: "products"
    label: "สินค้า"
    folder: "products"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "ชื่อสินค้า", name: "title", widget: "string" }
      - { label: "ขายดี", name: "bestseller", widget: "boolean", default: false }
      - { label: "ภาพสินค้า", name: "image", widget: "image" }
      - { label: "รายละเอียด", name: "description", widget: "text" }
      - { label: "หมวดหมู่", name: "category", widget: "string" }
      - label: "คุณสมบัติ"
        name: "features"
        widget: "list"
        field: { label: "คุณสมบัติ", name: "feature", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "product.njk" }